name: llmquiz
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_1
  - python=3.11.14=h981015d_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - beautifulsoup4==4.14.2
      - certifi==2025.11.12
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - fastapi==0.121.2
      - fonttools==4.60.1
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - numpy==2.3.4
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - playwright==1.56.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyee==13.0.0
      - pyparsing==3.2.5
      - pypdf2==3.0.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - starlette==0.49.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uvicorn==0.38.0
prefix: C:\Users\Rewa Shete\miniconda3\envs\llmquiz
